name: Sé Luné
favicon: null
layout_spectrum: 0.20808
typography_spectrum: 0.29237
title: se lune
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#595959'
    - '#779d36'
    - '#a1a1a1'
    - '#7b7b7b'
  brandStrength: 0
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
